[FEAT-4] Added deploy task for CircleCI

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -59,6 +59,21 @@ jobs:
           path: frontend/dist
           destination: frontend-staging-build
 
+
+  deploy-staging:
+    docker:
+      - image: cimg/base:current
+    steps:
+      - run:
+          name: Trigger Render Deployment
+          command: |
+            if [ -z "${RENDER_STAGING_DEPLOY_HOOK:-}" ]; then
+              echo "Error: RENDER_STAGING_DEPLOY_HOOK env var is missing."
+              exit 1
+            fi
+            # Hace la petición HTTP POST para iniciar el deploy
+            curl -X POST "$RENDER_STAGING_DEPLOY_HOOK"
+
 workflows:
   test-and-build:
     jobs:
@@ -66,6 +81,12 @@ workflows:
       - build-staging:
           requires:
             - verify
+          filters:
+            branches:
+              only: staging
+      - deploy-staging:
+          requires:
+            - build-staging
           filters:
             branches:
               only: staging
